version: '3'
services:
  app:
    container_name: rdvprefempt
    image: buildkite/puppeteer:5.2.1
    working_dir: /app
    volumes: 
      - './public:/app/public'
      - './src:/app/src'
      - './.env:/app/.env'
      - './deploy-entry.sh:/app/deploy-entry.sh'
      - './package.json:/app/package.json'
      - './package-lock.json:/app/package-lock.json'
    ports:
      - "3000:3000"
    command: 
        - sh
        - deploy-entry.sh
    networks:
      - caddy
  
networks:
  caddy:
    external:
      name: caddy-node_caddy