version: '3'
services:
  app:
    container_name: rdvprefmptcheck
    image: buildkite/puppeteer:5.2.1
    working_dir: /app
    volumes: 
      - './:/app'
    ports:
      - "3000:3000"
    command: 
        - npm
        - run
        - start
  